name: Docker Image CI

on:
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Azure Container Registry login and build
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.acrlogin }}
        # Container registry password
        password: ${{ secrets.acrpassword }}
        # Container registry server url
        login-server: ${{ secrets.acrserver }}
    - name: Build the Image
      run: |
       cd ${GITHUB_WORKSPACE}/ContainerApp/demoApp
       chmod +x increment_version.sh
       NEW_VERSION=$(./increment_version.sh)
       echo "The new version is $NEW_VERSION"
       echo "IMAGE_TAG=$NEW_VERSION" >> $GITHUB_ENV
       echo "the update version is ===============$NEW_VERSION"
       docker build . --file Dockerfile -t ${{ secrets.acrserver }}/srstest:v$NEW_VERSION
       
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: ${{ secrets.acrserver }}/srstest:v$NEW_VERSION
          format: 'sarif'
          output: 'trivy-results.sarif'
       
    - name: Push the Image
      run: |
       docker push ${{ secrets.acrserver }}/srstest:v$IMAGE_TAG
       

