name: Docker Image CI

on:
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Azure Container Registry login and build
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.acrlogin }}
        # Container registry password
        password: ${{ secrets.acrpassword }}
        # Container registry server url
        login-server: ${{ secrets.acrserver }}
    - run: |
       NEW_VERSION=$(./increment_version.sh)
       cd ${GITHUB_WORKSPACE}/ContainerApp/demoApp
       docker build . --file Dockerfile -t ${{ secrets.acrserver }}/srstest:v$NEW_VERSION
       docker push ${{ secrets.acrserver }}/srstest:v$NEW_VERSION
       
    # - name: Azure Container Registry Login
    #   uses: Azure/docker-login@v1
    #   with:
    #     # Container registry username
    #     username: ${{ secrets.acrlogin }}
    #     # Container registry password
    #     password: ${{ secrets.acrpassword }}
    #     # Container registry server url
    #     login-server: ${{ secrets.acrserver }}
    # - run: |
    #     docker push ${{ secrets.acrserver }}/srstest:${{ github.sha }}
