name: Confluent-Topic-Sync

# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      # Name of your Source Cosmos DB
      Environment:
        description: 'Enviroment to Sync with npr-prp,prp-prd'
        required: true
        default: 'npr-prp'
                  
      topic_list:
        description: 'List of Topics to Deploy--> , separated or set full for all topic to Deploy'
        required: true
        default: 'srs-test1'
     
      topic_deletelist:
        description: 'List of Topics to Delete--> , separated'
        required: true
        default: 'srs-test1,srs-test1'
  
jobs:
  #############################################################
  # This is packaging up the files from Git to the Artifacts files
  #############################################################
  Build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # Publish Artifact: Publish: Deployment-Scripts
    - name: 'Publish Artifact: Confluent Topic SYNC' 
      uses: actions/upload-artifact@v2
      with:
        name: 'deployment-scripts'
        path: '${{ github.workspace }}/Deployment-Scripts/Confluent-Sync/'
        
      
#############################################################
# Sync from NPR to PRP
#############################################################
  NPR-PRP:
    if: ${{ github.event.inputs.Environment == 'npr-prp' }}
    needs: Build
    runs-on: ubuntu-latest
    env:
       Confluent_Source_Server: 'pkc-epwny.eastus.azure.confluent.cloud'
       Confluent_Target_Server: 'pkc-epwny.eastus.azure.confluent.cloud'
       Confluent_Source_Cluster_Id: 'lkc-380qx0'
       Confluent_Target_Cluster_Id: 'lkc-do8dn1'
       keyVaultName-NPR: 'AKV-NPR'
       keyVaultName-PRP: 'AKV-PRP'
        
    steps:
    
    # Login to Azure
    - name: Login via Az module
      uses: Azure/login@v1.4.5
      with:
        creds: | 
          ${{ secrets.SP_NPR }}
          
    # Download secret from KeyVault Secrets
    - name: Download publish profile from KeyVault Secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ env.keyVaultName-PRP }}
        secrets: 'confluentcluster-kafka-prp-key,confluentcluster-kafka-prp-secretkey'
      id: ConfluentSecretActionPRP
  
    # Login to Azure
    - name: Login via Az module
      uses: Azure/login@v1.4.5
      with:
        creds: | 
          ${{ secrets.SP_NPR }}
          
    # Download secret from KeyVault Secrets
    - name: Download publish profile from KeyVault Secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ env.keyVaultName-NPR }}
        secrets: 'confluentcluster-kafka-npr-key,confluentcluster-kafka-npr-secretkey'
      id: ConfluentSecretActionNPR
      
    # Download Artifact: deployment-scripts
    - name: 'Download Artifact: Deployment Script' 
      uses: actions/download-artifact@v2
      with:
        name: 'deployment-scripts'
        path: ${{ github.workspace }}/Deployment-Scripts/Confluent-Sync/
        
    - name: Install dependencies
      run: |
        cd "$GITHUB_WORKSPACE/Deployment-Scripts/Confluent-Sync/"
        pip install -r requirements.txt
        
    - name: Sync Confluent Topics
      run: |
       chmod +x $GITHUB_WORKSPACE/Deployment-Scripts/Confluent-Sync/confluent_topics_deploy.py
       python3 $GITHUB_WORKSPACE/Deployment-Scripts/Confluent-Sync/confluent_topics_deploy.py
      env:
        source_api_key: ${{ steps.ConfluentSecretActionNPR.outputs.confluentcluster-kafka-npr-key }}
        source_api_secret: ${{ steps.ConfluentSecretActionNPR.outputs.confluentcluster-kafka-npr-secretkey }}
        target_api_key: ${{ steps.ConfluentSecretActionPRP.outputs.confluentcluster-kafka-prp-key }}
        target_api_secret: ${{ steps.ConfluentSecretActionPRP.outputs.confluentcluster-kafka-prp-secretkey }}
        source_server: ${{ env.Confluent_Source_Server }}
        target_server: ${{ env.Confluent_Target_Server }}
        source_cluster_id: ${{ env.Confluent_Source_Cluster_Id }}
        target_cluster_id: ${{ env.Confluent_Target_Cluster_Id }}
        topic_list: ${{ github.event.inputs.topic_list }}

#############################################################
# Sync from PRP to PRD
#############################################################
  PRP-PRD:
    if: ${{ github.event.inputs.Environment == 'prp-prd' }}
    needs: Build
    runs-on: ubuntu-latest
    env:
       Confluent_Source_Server: 'lkc-399xj-epwq2.southeastasia.azure.glb.confluent.cloud'
       Confluent_Target_Server: 'lkc-81m98r-lq99p.southeastasia.azure.glb.confluent.cloud'
       Confluent_Source_Cluster_Id: 'lkc-399xj'
       Confluent_Target_Cluster_Id: 'lkc-81m98r'
       keyVaultName-NPR: 'KEY-RG-SEA-CTRL-DX-NPR'
       keyVaultName-PRP: 'KEY-RG-SEA-CTRL-DX-PRP'
     
    steps:
    # Login to Azure
    - name: Login via Az module
      uses: Azure/login@v1.4.5
      with:
        creds: | 
          ${{ secrets.SP_PRD }}
          
    # Download secret from KeyVault Secrets
    - name: Download publish profile from KeyVault Secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ env.keyVaultName-PRD }}
        secrets: 'confluent-kafka-prd-key,confluent-kafka-prd-secretkey'
      id: ConfluentSecretActionPRD
  
    # Login to Azure
    - name: Login via Az module
      uses: Azure/login@v1.4.5
      with:
        creds: | 
          ${{ secrets.DATAX_SP_PRP }}
          
    # Download secret from KeyVault Secrets
    - name: Download publish profile from KeyVault Secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ env.keyVaultName-PRP }}
        secrets: 'confluent-kafka-prp-key,confluent-kafka-prp-secretkey'
      id: ConfluentSecretActionPRP
      
    # Download Artifact: deployment-scripts
    - name: 'Download Artifact: Deployment Script' 
      uses: actions/download-artifact@v2
      with:
        name: 'deployment-scripts'
        path: ${{ github.workspace }}/Deployment-Scripts/Confluent-Sync/
        
    - name: Install dependencies
      run: |
        cd "$GITHUB_WORKSPACE/Deployment-Scripts/Confluent-Sync/"
        pip install -r requirements.txt
        
    - name: Sync Confluent Topics
      run: |
       chmod +x $GITHUB_WORKSPACE/Deployment-Scripts/Confluent-Sync/confluent_topics_deploy.py
       python3 $GITHUB_WORKSPACE/Deployment-Scripts/Confluent-Sync/confluent_topics_deploy.py
      env:
        source_api_key: ${{ steps.ConfluentSecretActionNPR.outputs.confluent-kafka-prp-key }}
        source_api_secret: ${{ steps.ConfluentSecretActionNPR.outputs.confluent-kafka-prp-secretkey }}
        target_api_key: ${{ steps.ConfluentSecretActionPRP.outputs.confluent-kafka-prd-key }}
        target_api_secret: ${{ steps.ConfluentSecretActionPRP.outputs.confluent-kafka-prd-secretkey }}
        source_server: ${{ env.Confluent_Source_Server }}
        target_server: ${{ env.Confluent_Target_Server }}
        source_cluster_id: ${{ env.Confluent_Source_Cluster_Id }}
        target_cluster_id: ${{ env.Confluent_Target_Cluster_Id }}
        topic_list: ${{ github.event.inputs.topic_list }}
        topic_deletelist: "${{ github.event.inputs.topic_deletelist }}"
